services:
  ldap:
    image: osixia/openldap:1.5.0
    container_name: ldap
    ports:
      - 389:389
      - 636:636
    volumes:
      - ./ldap_data:/var/lib/ldap
      - ./ldap_config:/etc/ldap/slapd.d
    env_file:
      - ldap.env

  phpldapadmin:
    image: osixia/phpldapadmin:0.9.0
    container_name: ldap_admin
    ports:
      - 6443:443
    depends_on:
      - ldap  
    env_file:
      - ldap_admin.env
